#pragma warning disable CA1834 // Consider using 'StringBuilder.Append(char)' when applicable
#nullable disable
/*
 * Workflow2Service
 *
 * API Supporting the Workflow2 App
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: myemail@aisreview.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Text;
using System.Runtime.Serialization;
using System.Text.Json;

namespace CCC.CAS.Workflow2Messages.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class Workflow2SavedResponse : Workflow2, IEquatable<Workflow2SavedResponse>
    {
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Workflow2SavedResponse {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonSerializer.Serialize(this, new JsonSerializerOptions() { WriteIndented = true });
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Workflow2SavedResponse)obj);
        }

        /// <summary>
        /// Returns true if Workflow2SavedResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of Workflow2SavedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Workflow2SavedResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Workflow2SavedResponse left, Workflow2SavedResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Workflow2SavedResponse left, Workflow2SavedResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}

#pragma warning restore CA1834 // Consider using 'StringBuilder.Append(char)' when applicable

